#baseURL = 'https://about-hugo.github.io/hugo-bare-bones'
#baseURL = 'localhost:1313/hugo-bare-bones'
baseURL = '/'
languageCode = 'en-us'
title = 'Hugo Bare Bones'

# disable useful things to see a clean site structure
# for demo and learning
disableKinds = ['taxonomy', 'term', 'sitemap', 'RSS']