name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
        contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
  
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: hugo server -p 1318
