name: build, test, deploy pipeline

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo -b 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}'
      #https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
      - name: Upload Site
        uses: actions/upload-artifact@v4
        with:
          name: hugo_site
          path: ./public

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
  
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: hugo server -p 1318

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [test, build]  
    # https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download Site
        uses: actions/download-artifact@v4
        with:
          name: hugo_site
          path: ./public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
